fn main() {
    let dir = "docs/superpowers/specs/grammar/tree-sitter-ascript/src";
    println!("cargo:rerun-if-changed={}/parser.c", dir);
    cc::Build::new()
        .include(dir)
        .file(format!("{}/parser.c", dir))
        .warnings(false)
        .compile("tree_sitter_ascript");

    generate_ast_nodes();
}

/// Emit one typed wrapper struct per CONCRETE node rule (skip pure Alt rules like Stmt/Expr —
/// those become enums in a later task).
///
/// Locked ungrammar API (version 1.x):
///   - Parse:       `text.parse::<ungrammar::Grammar>()` via `FromStr`
///   - Iterate:     `grammar.iter()` → `impl Iterator<Item = ungrammar::Node>`
///   - Index:       `&grammar[node]` → `&ungrammar::NodeData { name: String, rule: Rule }`
///   - Alt detect:  `matches!(&grammar[node].rule, ungrammar::Rule::Alt(_))`
///   - Rule::Alt(Vec<Rule>), Rule::Seq(Vec<Rule>), Rule::Node(Node), Rule::Token(Token),
///     Rule::Opt(Box<Rule>), Rule::Rep(Box<Rule>), Rule::Labeled { label, rule }
fn generate_ast_nodes() {
    use std::fmt::Write as _;
    println!("cargo:rerun-if-changed=src/syntax/ast/ascript.ungram");
    let text =
        std::fs::read_to_string("src/syntax/ast/ascript.ungram").expect("read ascript.ungram");
    let grammar: ungrammar::Grammar = text.parse().expect("parse ungrammar");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from ascript.ungram — do not edit.\n");
    // Use ResolvedNode throughout: parse_to_tree returns ResolvedNode, and
    // ResolvedNode::descendants() yields &ResolvedNode, so cast() takes/stores ResolvedNode.
    // ResolvedNode also implements Deref<Target = SyntaxNode>, so .kind() is accessible.
    out.push_str("use crate::syntax::cst::{ResolvedNode, ResolvedToken};\n");
    out.push_str("use crate::syntax::kind::SyntaxKind;\n");
    out.push_str("use crate::syntax::ast::support::{self, AstNode};\n\n");

    for node in grammar.iter() {
        let data = &grammar[node];
        let name = &data.name;
        // A token-only alternation (e.g. `Literal = 'number' | 'string' | …`) is a real
        // leaf CST node kind, but it has no node-ref children — so we emit it as a plain
        // concrete struct (falling through below), NOT as a Rust enum.
        if is_enum_rule(&grammar, node) && !alt_variants(&grammar, node).is_empty() {
            // Node-reference variants of this alternation become enum arms.
            let variants: Vec<String> = alt_variants(&grammar, node);
            let _ = writeln!(out, "#[derive(Debug, Clone)]");
            let _ = writeln!(out, "pub enum {name} {{");
            for v in &variants {
                let _ = writeln!(out, "    {v}({v}),");
            }
            let _ = writeln!(out, "}}");
            let _ = writeln!(out, "impl {name} {{");
            let _ = writeln!(
                out,
                "    pub fn cast(node: ResolvedNode) -> Option<Self> {{"
            );
            let _ = writeln!(out, "        match node.kind() {{");
            for v in &variants {
                let _ = writeln!(
                    out,
                    "            SyntaxKind::{v} => {v}::cast(node).map(Self::{v}),"
                );
            }
            let _ = writeln!(out, "            _ => None,");
            let _ = writeln!(out, "        }}");
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}");
            // Also implement the AstNode trait so enums work with the generic
            // child helpers. `syntax()` delegates to the active variant.
            let _ = writeln!(out, "impl AstNode for {name} {{");
            let _ = writeln!(
                out,
                "    fn cast(node: ResolvedNode) -> Option<Self> {{ {name}::cast(node) }}"
            );
            let _ = writeln!(out, "    fn syntax(&self) -> &ResolvedNode {{");
            let _ = writeln!(out, "        match self {{");
            for v in &variants {
                let _ = writeln!(out, "            Self::{v}(inner) => inner.syntax(),");
            }
            let _ = writeln!(out, "        }}");
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}\n");
            continue;
        }
        let _ = writeln!(out, "#[derive(Debug, Clone)]");
        let _ = writeln!(out, "pub struct {name}(pub ResolvedNode);");
        let _ = writeln!(out, "impl {name} {{");
        let _ = writeln!(
            out,
            "    pub fn cast(node: ResolvedNode) -> Option<Self> {{"
        );
        let _ = writeln!(
            out,
            "        if node.kind() == SyntaxKind::{name} {{ Some(Self(node)) }} else {{ None }}"
        );
        let _ = writeln!(out, "    }}");
        let _ = writeln!(
            out,
            "    pub fn syntax(&self) -> &ResolvedNode {{ &self.0 }}"
        );
        // Data-driven typed child accessors derived from this node's rule shape.
        emit_accessors(&grammar, node, &mut out);
        let _ = writeln!(out, "}}");
        let _ = writeln!(out, "impl AstNode for {name} {{");
        let _ = writeln!(
            out,
            "    fn cast(node: ResolvedNode) -> Option<Self> {{ {name}::cast(node) }}"
        );
        let _ = writeln!(out, "    fn syntax(&self) -> &ResolvedNode {{ &self.0 }}");
        let _ = writeln!(out, "}}\n");
    }

    let dest = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("ast_nodes.rs");
    std::fs::write(dest, out).expect("write ast_nodes.rs");
}

/// A rule is an "enum" (pure alternation) if its top-level rule is an `Alt`.
fn is_enum_rule(grammar: &ungrammar::Grammar, node: ungrammar::Node) -> bool {
    matches!(&grammar[node].rule, ungrammar::Rule::Alt(_))
}

/// Collect the node names referenced by an `Alt` rule (e.g. `Expr = A | B | C`).
/// Only `Rule::Node` references are collected; token alternatives are ignored.
fn alt_variants(grammar: &ungrammar::Grammar, node: ungrammar::Node) -> Vec<String> {
    fn collect(grammar: &ungrammar::Grammar, rule: &ungrammar::Rule, out: &mut Vec<String>) {
        match rule {
            ungrammar::Rule::Alt(rules) => {
                for r in rules {
                    collect(grammar, r, out);
                }
            }
            ungrammar::Rule::Node(n) => out.push(grammar[*n].name.clone()),
            _ => {}
        }
    }
    let mut out = Vec::new();
    collect(grammar, &grammar[node].rule, &mut out);
    out
}

/// One typed child slot extracted from a node's rule.
struct Field {
    /// Accessor method name.
    method: String,
    /// Referenced node type (Rust struct/enum name).
    ty: String,
    /// True when the child can occur 0..N times (`Rep`) → emit an iterator.
    repeated: bool,
    /// 0-based position among same-typed siblings (for `nth_child` disambiguation).
    index: usize,
}

/// A token slot: either an operator alternation (`op:('+'|'-'|...)`) or a single
/// significant keyword/ident token we want a `_token()` accessor for.
struct TokenField {
    method: String,
    /// SyntaxKind variant names this token may take.
    kinds: Vec<String>,
    /// When true the slot is an alternation → `op()`-style returning the kind.
    is_alt: bool,
}

/// Map an ungrammar token NAME (its literal spelling, e.g. "+", "let", "ident")
/// to the matching `SyntaxKind` variant name. Returns `None` for spellings we
/// don't surface as accessors.
fn token_kind(name: &str) -> Option<&'static str> {
    Some(match name {
        "+" => "Plus",
        "-" => "Minus",
        "*" => "Star",
        "/" => "Slash",
        "%" => "Percent",
        "**" => "StarStar",
        "(" => "LParen",
        ")" => "RParen",
        "{" => "LBrace",
        "}" => "RBrace",
        "[" => "LBracket",
        "]" => "RBracket",
        "," => "Comma",
        "." => "Dot",
        ":" => "Colon",
        ";" => "Semicolon",
        "!" => "Bang",
        "!=" => "BangEq",
        "==" => "EqEq",
        "=" => "Eq",
        "<" => "Lt",
        "<=" => "Le",
        ">" => "Gt",
        ">=" => "Ge",
        "&&" => "AmpAmp",
        "||" => "PipePipe",
        "??" => "QuestionQuestion",
        "?" => "Question",
        "?." => "QuestionDot",
        "|" => "Pipe",
        "+=" => "PlusEq",
        "-=" => "MinusEq",
        "*=" => "StarEq",
        "/=" => "SlashEq",
        ".." => "DotDot",
        "..=" => "DotDotEq",
        "..." => "DotDotDot",
        "=>" => "FatArrow",
        "true" => "TrueKw",
        "false" => "FalseKw",
        "nil" => "NilKw",
        "let" => "LetKw",
        "const" => "ConstKw",
        "if" => "IfKw",
        "else" => "ElseKw",
        "while" => "WhileKw",
        "for" => "ForKw",
        "in" => "InKw",
        "of" => "OfKw",
        "return" => "ReturnKw",
        "break" => "BreakKw",
        "continue" => "ContinueKw",
        "fn" => "FnKw",
        "enum" => "EnumKw",
        "match" => "MatchKw",
        "class" => "ClassKw",
        "import" => "ImportKw",
        "export" => "ExportKw",
        "async" => "AsyncKw",
        "await" => "AwaitKw",
        "yield" => "YieldKw",
        "number" => "Number",
        "string" => "Str",
        "ident" => "Ident",
        "template" => "TemplateStr",
        _ => return None,
    })
}

/// Escape a method name that collides with a Rust keyword (e.g. `type` → `r#type`).
fn safe_method(name: &str) -> String {
    // Raw-identifier-able keywords that can appear as derived method names.
    const KW: &[&str] = &[
        "type", "match", "if", "else", "for", "while", "return", "break", "continue", "fn", "let",
        "const", "enum", "impl", "struct", "in", "loop", "move", "ref",
    ];
    if KW.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

/// Convert a PascalCase node type name to snake_case (ObjPatEntry → obj_pat_entry,
/// Expr → expr, NameRef → name_ref). Used to derive field names from node types.
fn to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// Plural method name for a repeated child of type `ty` (Expr → exprs, Stmt → stmts,
/// Param → params). Naive but adequate for the grammar's node names.
fn plural(ty: &str) -> String {
    let base = to_snake(ty);
    if base.ends_with('s') {
        format!("{base}es")
    } else {
        format!("{base}s")
    }
}

/// Walk a node's rule and emit typed child accessors (node children + tokens).
fn emit_accessors(grammar: &ungrammar::Grammar, node: ungrammar::Node, out: &mut String) {
    use std::fmt::Write as _;
    use ungrammar::Rule;

    let mut node_fields: Vec<Field> = Vec::new();
    let mut token_fields: Vec<TokenField> = Vec::new();
    // Per-type running count, so the i-th `Expr` child gets index i for nth_child.
    let mut type_counts: std::collections::HashMap<String, usize> =
        std::collections::HashMap::new();

    // Walk a rule, threading the current label down so `lhs:Expr` names the field.
    fn walk(
        grammar: &ungrammar::Grammar,
        rule: &Rule,
        label: Option<&str>,
        repeated: bool,
        node_fields: &mut Vec<Field>,
        token_fields: &mut Vec<TokenField>,
        type_counts: &mut std::collections::HashMap<String, usize>,
    ) {
        match rule {
            Rule::Labeled { label, rule } => {
                walk(
                    grammar,
                    rule,
                    Some(label),
                    repeated,
                    node_fields,
                    token_fields,
                    type_counts,
                );
            }
            Rule::Seq(rules) => {
                for r in rules {
                    walk(
                        grammar,
                        r,
                        None,
                        repeated,
                        node_fields,
                        token_fields,
                        type_counts,
                    );
                }
            }
            Rule::Opt(inner) => {
                // Optional doesn't change arity for our purposes (single → Option<T>).
                walk(
                    grammar,
                    inner,
                    label,
                    repeated,
                    node_fields,
                    token_fields,
                    type_counts,
                );
            }
            Rule::Rep(inner) => {
                walk(
                    grammar,
                    inner,
                    label,
                    true,
                    node_fields,
                    token_fields,
                    type_counts,
                );
            }
            Rule::Node(n) => {
                let ty = grammar[*n].name.clone();
                let idx = *type_counts.get(&ty).unwrap_or(&0);
                *type_counts.entry(ty.clone()).or_insert(0) += 1;
                let method = match label {
                    Some(l) => l.to_string(),
                    None if repeated => plural(&ty),
                    None => to_snake(&ty),
                };
                node_fields.push(Field {
                    method,
                    ty,
                    repeated,
                    index: idx,
                });
            }
            Rule::Token(t) => {
                // Single significant token. Only surface ident/keyword/literal tokens
                // (punctuation accessors aren't useful for the compiler).
                let spelling = &grammar[*t].name;
                if let Some(kind) = token_kind(spelling) {
                    // Skip pure structural punctuation; keep ident/kw/literals.
                    let useful = matches!(
                        spelling.as_str(),
                        "ident" | "number" | "string" | "template"
                    ) || kind.ends_with("Kw");
                    if useful {
                        let method = if spelling == "ident" {
                            "ident_token".to_string()
                        } else {
                            format!("{}_token", to_snake(kind.trim_end_matches("Kw")))
                        };
                        token_fields.push(TokenField {
                            method,
                            kinds: vec![kind.to_string()],
                            is_alt: false,
                        });
                    }
                }
            }
            Rule::Alt(alts) => {
                // An alternation directly inside a node rule is an operator slot
                // when every alternative is a token (e.g. op:('+'|'-'|...)).
                let all_tokens = alts.iter().all(|a| matches!(a, Rule::Token(_)));
                if all_tokens && !alts.is_empty() {
                    let mut kinds = Vec::new();
                    for a in alts {
                        if let Rule::Token(t) = a {
                            if let Some(k) = token_kind(&grammar[*t].name) {
                                kinds.push(k.to_string());
                            }
                        }
                    }
                    if !kinds.is_empty() {
                        let method = label.unwrap_or("op").to_string();
                        token_fields.push(TokenField {
                            method,
                            kinds,
                            is_alt: true,
                        });
                    }
                } else {
                    // Mixed alt of nodes/tokens (e.g. `Block | Expr`): recurse so each
                    // node alternative still gets a single-child accessor.
                    for a in alts {
                        walk(
                            grammar,
                            a,
                            label,
                            repeated,
                            node_fields,
                            token_fields,
                            type_counts,
                        );
                    }
                }
            }
        }
    }

    walk(
        grammar,
        &grammar[node].rule,
        None,
        false,
        &mut node_fields,
        &mut token_fields,
        &mut type_counts,
    );

    // Dedupe method names defensively (a mixed alt could yield duplicate node
    // accessors for the same type; keep the first).
    let mut seen = std::collections::HashSet::new();
    for f in &node_fields {
        let method = safe_method(&f.method);
        if !seen.insert(method.clone()) {
            continue;
        }
        if f.repeated {
            let _ = writeln!(
                out,
                "    pub fn {m}(&self) -> impl Iterator<Item = {ty}> + '_ {{ support::children(&self.0) }}",
                m = method,
                ty = f.ty
            );
        } else {
            // Use nth_child when ≥1 sibling shares this type, else child().
            let same_type = node_fields
                .iter()
                .filter(|g| g.ty == f.ty && !g.repeated)
                .count();
            if same_type > 1 {
                let _ = writeln!(
                    out,
                    "    pub fn {m}(&self) -> Option<{ty}> {{ support::nth_child(&self.0, {i}) }}",
                    m = method,
                    ty = f.ty,
                    i = f.index
                );
            } else {
                let _ = writeln!(
                    out,
                    "    pub fn {m}(&self) -> Option<{ty}> {{ support::child(&self.0) }}",
                    m = method,
                    ty = f.ty
                );
            }
        }
    }
    for tf in &token_fields {
        let method = safe_method(&tf.method);
        if !seen.insert(method.clone()) {
            continue;
        }
        if tf.is_alt {
            let kinds: Vec<String> = tf
                .kinds
                .iter()
                .map(|k| format!("SyntaxKind::{k}"))
                .collect();
            let _ = writeln!(
                out,
                "    pub fn {m}(&self) -> Option<SyntaxKind> {{ support::token_in(&self.0, &[{ks}]).map(|t| t.kind()) }}",
                m = method,
                ks = kinds.join(", ")
            );
        } else {
            let _ = writeln!(
                out,
                "    pub fn {m}(&self) -> Option<ResolvedToken> {{ support::token(&self.0, SyntaxKind::{k}) }}",
                m = method,
                k = tf.kinds[0]
            );
        }
    }
}
