fn main() {
    let dir = "docs/superpowers/specs/grammar/tree-sitter-ascript/src";
    println!("cargo:rerun-if-changed={}/parser.c", dir);
    cc::Build::new()
        .include(dir)
        .file(format!("{}/parser.c", dir))
        .warnings(false)
        .compile("tree_sitter_ascript");

    generate_ast_nodes();
}

/// Emit one typed wrapper struct per CONCRETE node rule (skip pure Alt rules like Stmt/Expr —
/// those become enums in a later task).
///
/// Locked ungrammar API (version 1.x):
///   - Parse:       `text.parse::<ungrammar::Grammar>()` via `FromStr`
///   - Iterate:     `grammar.iter()` → `impl Iterator<Item = ungrammar::Node>`
///   - Index:       `&grammar[node]` → `&ungrammar::NodeData { name: String, rule: Rule }`
///   - Alt detect:  `matches!(&grammar[node].rule, ungrammar::Rule::Alt(_))`
///   - Rule::Alt(Vec<Rule>), Rule::Seq(Vec<Rule>), Rule::Node(Node), Rule::Token(Token),
///     Rule::Opt(Box<Rule>), Rule::Rep(Box<Rule>), Rule::Labeled { label, rule }
fn generate_ast_nodes() {
    use std::fmt::Write as _;
    println!("cargo:rerun-if-changed=src/syntax/ast/ascript.ungram");
    let text = std::fs::read_to_string("src/syntax/ast/ascript.ungram")
        .expect("read ascript.ungram");
    let grammar: ungrammar::Grammar = text.parse().expect("parse ungrammar");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from ascript.ungram — do not edit.\n");
    // Use ResolvedNode throughout: parse_to_tree returns ResolvedNode, and
    // ResolvedNode::descendants() yields &ResolvedNode, so cast() takes/stores ResolvedNode.
    // ResolvedNode also implements Deref<Target = SyntaxNode>, so .kind() is accessible.
    out.push_str("use crate::syntax::cst::ResolvedNode;\n");
    out.push_str("use crate::syntax::kind::SyntaxKind;\n\n");

    for node in grammar.iter() {
        let data = &grammar[node];
        let name = &data.name;
        if is_enum_rule(&grammar, node) {
            // Collect node-reference variants, but exclude any node that is itself a
            // pure-token alt (e.g. `Literal = 'number' | 'string' | …`) — those have no
            // generated Rust type and would cause `Literal::cast(...)` compile errors.
            let variants: Vec<String> = alt_variants(&grammar, node)
                .into_iter()
                .filter(|v| {
                    // Keep the variant only if it resolves to a generated type:
                    // either a concrete (non-alt) node, or an alt with ≥1 node-ref variant.
                    !is_node_a_skipped_alt(&grammar, v)
                })
                .collect();
            // Skip emitting an enum when there are no usable variants.
            if variants.is_empty() {
                continue;
            }
            let _ = writeln!(out, "#[derive(Debug, Clone)]");
            let _ = writeln!(out, "pub enum {name} {{");
            for v in &variants {
                let _ = writeln!(out, "    {v}({v}),");
            }
            let _ = writeln!(out, "}}");
            let _ = writeln!(out, "impl {name} {{");
            let _ = writeln!(out, "    pub fn cast(node: ResolvedNode) -> Option<Self> {{");
            let _ = writeln!(out, "        match node.kind() {{");
            for v in &variants {
                let _ = writeln!(
                    out,
                    "            SyntaxKind::{v} => {v}::cast(node).map(Self::{v}),"
                );
            }
            let _ = writeln!(out, "            _ => None,");
            let _ = writeln!(out, "        }}");
            let _ = writeln!(out, "    }}");
            let _ = writeln!(out, "}}\n");
            continue;
        }
        let _ = writeln!(out, "#[derive(Debug, Clone)]");
        let _ = writeln!(out, "pub struct {name}(pub ResolvedNode);");
        let _ = writeln!(out, "impl {name} {{");
        let _ = writeln!(out, "    pub fn cast(node: ResolvedNode) -> Option<Self> {{");
        let _ = writeln!(
            out,
            "        if node.kind() == SyntaxKind::{name} {{ Some(Self(node)) }} else {{ None }}"
        );
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "    pub fn syntax(&self) -> &ResolvedNode {{ &self.0 }}");
        let _ = writeln!(out, "}}\n");
    }

    let dest = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("ast_nodes.rs");
    std::fs::write(dest, out).expect("write ast_nodes.rs");
}

/// A rule is an "enum" (pure alternation) if its top-level rule is an `Alt`.
fn is_enum_rule(grammar: &ungrammar::Grammar, node: ungrammar::Node) -> bool {
    matches!(&grammar[node].rule, ungrammar::Rule::Alt(_))
}

/// Returns true if the named node is an alt rule whose `alt_variants` is empty — i.e. a
/// pure-token alt like `Literal = 'number' | 'string' | …`.  Such nodes have no generated
/// Rust type and must be excluded from parent enum variant lists.
fn is_node_a_skipped_alt(grammar: &ungrammar::Grammar, name: &str) -> bool {
    for n in grammar.iter() {
        if grammar[n].name == name {
            return is_enum_rule(grammar, n) && alt_variants(grammar, n).is_empty();
        }
    }
    false
}

/// Collect the node names referenced by an `Alt` rule (e.g. `Expr = A | B | C`).
/// Only `Rule::Node` references are collected; token alternatives are ignored.
fn alt_variants(grammar: &ungrammar::Grammar, node: ungrammar::Node) -> Vec<String> {
    fn collect(grammar: &ungrammar::Grammar, rule: &ungrammar::Rule, out: &mut Vec<String>) {
        match rule {
            ungrammar::Rule::Alt(rules) => {
                for r in rules {
                    collect(grammar, r, out);
                }
            }
            ungrammar::Rule::Node(n) => out.push(grammar[*n].name.clone()),
            _ => {}
        }
    }
    let mut out = Vec::new();
    collect(grammar, &grammar[node].rule, &mut out);
    out
}
