fn main() {
    let dir = "docs/superpowers/specs/grammar/tree-sitter-ascript/src";
    println!("cargo:rerun-if-changed={}/parser.c", dir);
    cc::Build::new()
        .include(dir)
        .file(format!("{}/parser.c", dir))
        .warnings(false)
        .compile("tree_sitter_ascript");

    generate_ast_nodes();
}

/// Emit one typed wrapper struct per CONCRETE node rule (skip pure Alt rules like Stmt/Expr —
/// those become enums in a later task).
///
/// Locked ungrammar API (version 1.x):
///   - Parse:       `text.parse::<ungrammar::Grammar>()` via `FromStr`
///   - Iterate:     `grammar.iter()` → `impl Iterator<Item = ungrammar::Node>`
///   - Index:       `&grammar[node]` → `&ungrammar::NodeData { name: String, rule: Rule }`
///   - Alt detect:  `matches!(&grammar[node].rule, ungrammar::Rule::Alt(_))`
///   - Rule::Alt(Vec<Rule>), Rule::Seq(Vec<Rule>), Rule::Node(Node), Rule::Token(Token),
///     Rule::Opt(Box<Rule>), Rule::Rep(Box<Rule>), Rule::Labeled { label, rule }
fn generate_ast_nodes() {
    use std::fmt::Write as _;
    println!("cargo:rerun-if-changed=src/syntax/ast/ascript.ungram");
    let text = std::fs::read_to_string("src/syntax/ast/ascript.ungram")
        .expect("read ascript.ungram");
    let grammar: ungrammar::Grammar = text.parse().expect("parse ungrammar");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from ascript.ungram — do not edit.\n");
    // Use ResolvedNode throughout: parse_to_tree returns ResolvedNode, and
    // ResolvedNode::descendants() yields &ResolvedNode, so cast() takes/stores ResolvedNode.
    // ResolvedNode also implements Deref<Target = SyntaxNode>, so .kind() is accessible.
    out.push_str("use crate::syntax::cst::ResolvedNode;\n");
    out.push_str("use crate::syntax::kind::SyntaxKind;\n\n");

    for node in grammar.iter() {
        let data = &grammar[node];
        let name = &data.name;
        if is_enum_rule(&grammar, node) {
            // Pure Alt rules (Stmt, Expr, Literal) become enums in a later task.
            continue;
        }
        let _ = writeln!(out, "#[derive(Debug, Clone)]");
        let _ = writeln!(out, "pub struct {name}(pub ResolvedNode);");
        let _ = writeln!(out, "impl {name} {{");
        let _ = writeln!(out, "    pub fn cast(node: ResolvedNode) -> Option<Self> {{");
        let _ = writeln!(
            out,
            "        if node.kind() == SyntaxKind::{name} {{ Some(Self(node)) }} else {{ None }}"
        );
        let _ = writeln!(out, "    }}");
        let _ = writeln!(out, "    pub fn syntax(&self) -> &ResolvedNode {{ &self.0 }}");
        let _ = writeln!(out, "}}\n");
    }

    let dest = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("ast_nodes.rs");
    std::fs::write(dest, out).expect("write ast_nodes.rs");
}

/// A rule is an "enum" (pure alternation) if its top-level rule is an `Alt`.
fn is_enum_rule(grammar: &ungrammar::Grammar, node: ungrammar::Node) -> bool {
    matches!(&grammar[node].rule, ungrammar::Rule::Alt(_))
}
