#!/usr/bin/env bash
# bench/run_call_bench.sh
#
# CALL baseline harness + per-item A/B (CALL §6, plan Task 0.1 + Task 4.1).
#
# Measures wall time + peak RSS for the functional-idiom workloads that are the
# primary CALL targets (func_pipeline, call_heavy) and three supporting workloads
# (object_churn, json_roundtrip, server_request) under the release binary.
#
# Each workload is run RUNS times; the script reports the MEDIAN wall time and the
# RSS from the final run (RSS is stable run-to-run; timing is subject to thermal
# drift, so median over RUNS cancels outliers while staying fast).
#
# Usage:
#   ./bench/run_call_bench.sh            # 5 runs per workload (default)
#   RUNS=7 ./bench/run_call_bench.sh     # override run count
#   BINARY=path/to/ascript ./bench/run_call_bench.sh  # custom binary
#
# Output:
#   bench/CALL_RESULTS.md  (section APPENDED; run after each phase)
#   A summary table to stdout.
#
# bash 3 compatible (macOS default).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
RESULTS_FILE="${SCRIPT_DIR}/CALL_RESULTS.md"
BINARY="${BINARY:-${REPO_ROOT}/target/release/ascript}"
RUNS="${RUNS:-5}"

BENCHES="func_pipeline call_heavy object_churn json_roundtrip server_request"

# ── build ─────────────────────────────────────────────────────────────────────
echo "==> Building release binary..."
cd "${REPO_ROOT}"
cargo build --release --quiet
echo "    Built: ${BINARY}"
echo ""

# ── host info ─────────────────────────────────────────────────────────────────
TIMESTAMP="$(date -u '+%Y-%m-%d %H:%M UTC')"
CPU_MODEL="$(sysctl -n machdep.cpu.brand_string 2>/dev/null || \
             lscpu 2>/dev/null | awk -F: '/Model name/{gsub(/^[ \t]+/,"",$2); print $2}' || \
             echo 'unknown')"
CPU_CORES="$(sysctl -n hw.logicalcpu 2>/dev/null || nproc 2>/dev/null || echo '?')"
OS_INFO="$(uname -srm)"
GIT_SHA="$(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || echo 'unknown')"

echo "Host: ${CPU_MODEL} (${CPU_CORES} logical cores) / ${OS_INFO}"
echo "Binary: ${BINARY} (${GIT_SHA})"
echo "Runs per workload: ${RUNS}"
echo ""

# ── helpers ───────────────────────────────────────────────────────────────────
median() {
    # Read stdin lines as numbers, return the median (rounded to integer ms).
    sort -n | awk '{a[NR]=$1} END {printf "%d", a[int((NR+1)/2)]}'
}

run_ms() {
    # Extract elapsed_ms from one run of a workload.
    "${BINARY}" run "${SCRIPT_DIR}/profiling/$1.as" 2>/dev/null \
        | grep -oE 'elapsed_ms=[0-9.]+' | cut -d= -f2
}

peak_rss_mb() {
    # Peak RSS in MB from /usr/bin/time -l (macOS).
    local bytes
    bytes=$(/usr/bin/time -l "${BINARY}" run "${SCRIPT_DIR}/profiling/$1.as" 2>&1 >/dev/null \
        | grep -i "maximum resident" | grep -oE '[0-9]+' | head -1)
    awk -v b="${bytes:-0}" 'BEGIN { printf "%d", b / 1048576 }'
}

# ── run workloads ─────────────────────────────────────────────────────────────
echo "==> Running workloads (${RUNS} runs each)..."
printf "%-20s | %10s | %7s\n" "workload" "median ms" "RSS MB"
printf "%-20s-+-%10s-+-%7s\n" "--------------------" "----------" "-------"

# Store results as parallel arrays using a temp file (bash 3 compat)
TMPDATA="$(mktemp /tmp/ascript-call-bench.XXXXXX)"
trap 'rm -f "${TMPDATA}"' EXIT

for bench in ${BENCHES}; do
    times=""
    for r in $(seq 1 "${RUNS}"); do
        t="$(run_ms "${bench}" 2>/dev/null || true)"
        if [[ -n "${t}" ]]; then
            times="${times}${t}"$'\n'
        fi
    done
    if [[ -z "${times}" ]]; then
        med="???"
        rss_mb="?"
    else
        med="$(echo "${times}" | grep -v '^$' | median)"
        rss_mb="$(peak_rss_mb "${bench}")"
    fi
    printf "%-20s | %10s | %7s\n" "${bench}" "${med}" "${rss_mb}"
    echo "${bench} ${med} ${rss_mb}" >> "${TMPDATA}"
done
echo ""

# ── append to CALL_RESULTS.md ─────────────────────────────────────────────────
LABEL="${BENCH_LABEL:-Baseline (pre-CALL, same session)}"

{
    echo ""
    echo "## ${LABEL}"
    echo ""
    echo "**Date:** ${TIMESTAMP}"
    echo "**Host:** ${CPU_MODEL} (${CPU_CORES} logical cores)"
    echo "**OS:** ${OS_INFO}"
    echo "**Binary:** \`target/release/ascript\` @ \`${GIT_SHA}\`"
    echo "**Runs per workload (median):** ${RUNS}"
    echo ""
    echo "| workload | median ms | RSS MB |"
    echo "|----------|----------:|-------:|"
    while IFS=' ' read -r bench med rss_mb; do
        printf "| %-18s | %9s | %6s |\n" "${bench}" "${med}" "${rss_mb}"
    done < "${TMPDATA}"
    echo ""
    echo "*Generated by \`bench/run_call_bench.sh\`.*"
} >> "${RESULTS_FILE}"

echo "==> Results appended to ${RESULTS_FILE}"
