import * as set from "std/set"
import * as decimal from "std/decimal"
let s1 = set.from([1, 1, 2, 3])
assert(set.size(s1) == 3, "dedup: size 3")
assert(len(s1) == 3, "len() works on sets")
assert(set.has(s1, 1) == true, "has 1")
assert(set.has(s1, 99) == false, "no 99")
set.add(s1, 99)
assert(set.has(s1, 99) == true, "add 99")
let deleted = set.delete(s1, 99)
assert(deleted == true, "delete returns true when found")
assert(set.has(s1, 99) == false, "99 removed")
assert(set.delete(s1, 99) == false, "delete non-existent returns false")
let s_ordered = set.from(["c", "a", "b"])
let vals = set.values(s_ordered)
assert(vals[0] == "c", "values[0]")
assert(vals[1] == "a", "values[1]")
assert(vals[2] == "b", "values[2]")
let a = set.from([1, 2, 3])
let b = set.from([2, 3, 4])
let u = set.union(a, b)
assert(set.size(u) == 4, "union size 4")
assert(set.has(u, 1) == true, "union has 1")
assert(set.has(u, 4) == true, "union has 4")
let inter = set.intersection(a, b)
assert(set.size(inter) == 2, "intersection size 2")
assert(set.has(inter, 2) == true, "intersection has 2")
assert(set.has(inter, 3) == true, "intersection has 3")
assert(set.has(inter, 1) == false, "intersection lacks 1")
let diff = set.difference(a, b)
assert(set.size(diff) == 1, "difference size 1")
assert(set.has(diff, 1) == true, "difference has 1")
assert(set.has(diff, 2) == false, "difference lacks 2")
assert(set.size(a) == 3, "a unchanged after operations")
assert(set.size(b) == 3, "b unchanged after operations")
let bad_add = recover(() => set.add(set.new(), [1, 2]))
assert(bad_add[1] != nil, "non-hashable element panics")
let d01 = decimal.from("0.1")
let d02 = decimal.from("0.2")
let d03 = decimal.from("0.3")
assert(d01 + d02 == d03, "0.1 + 0.2 == 0.3 exactly")
let di = decimal.from(42)
assert(decimal.toString(di) == "42", "from integer")
let df = decimal.from("1.50")
assert(decimal.toString(df) == "1.50", "toString preserves scale")
let dn = decimal.toNumber(decimal.from("3.5"))
assert(dn == 3.5, "toNumber")
let x = decimal.from("10")
let y = decimal.from("3")
assert(decimal.toString(x + y) == "13", "add")
assert(decimal.toString(x - y) == "7", "sub")
assert(decimal.toString(x * y) == "30", "mul")
let scale = decimal.from("2.5") * 4
assert(decimal.toString(scale) == "10.0", "decimal * number")
assert(decimal.from("1.5") < decimal.from("2.0"), "lt")
assert(decimal.from("2.0") > decimal.from("1.5"), "gt")
assert(decimal.from("1.5") <= decimal.from("1.5"), "le")
assert(decimal.from("1.5") >= decimal.from("1.5"), "ge")
assert(decimal.from("1") == decimal.from("1"), "eq")
assert(decimal.from("1") != decimal.from("2"), "ne")
assert(decimal.from("5") == 5, "cross-type ==")
assert(decimal.from("5") != 6, "cross-type !=")
assert(decimal.round(decimal.from("1.5")) == decimal.from("2"), "round 1.5 -> 2")
assert(decimal.round(decimal.from("2.5")) == decimal.from("3"), "round 2.5 -> 3")
assert(decimal.round(decimal.from("-1.5")) == decimal.from("-2"), "round -1.5 -> -2")
assert(decimal.round(decimal.from("1.456"), 2) == decimal.from("1.46"), "round to 2 places")
assert(decimal.abs(decimal.from("-3.7")) == decimal.from("3.7"), "abs")
assert(decimal.floor(decimal.from("1.9")) == decimal.from("1"), "floor")
assert(decimal.ceil(decimal.from("1.1")) == decimal.from("2"), "ceil")
assert(decimal.trunc(decimal.from("-1.9")) == decimal.from("-1"), "trunc")
import * as array from "std/array"
let prices = ["9.99", "4.50", "0.01"]
let total = array.reduce(array.map(prices, p => decimal.from(p)), (acc, p) => acc + p, decimal.from("0"))
assert(decimal.toString(total) == "14.50", "exact price total")
let [good, e1] = decimal.parse("3.14")
assert(e1 == nil, "parse valid ok")
assert(decimal.toString(good) == "3.14", "parse value correct")
let [bad, e2] = decimal.parse("not-a-number")
assert(bad == nil, "parse invalid -> nil")
assert(e2 != nil, "parse invalid -> err")
assert(e2.message != nil, "parse err has message")
let panic_from = recover(() => decimal.from("xyz"))
assert(panic_from[1] != nil, "from invalid string panics")
print("core types: all assertions passed")
